# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 797afdecdd739fe20fd7b6851bca005302f7fb41fdfe8f13f762621016a180eed056fa3c6948a5a46bf5dad0d89e65a988744e467ffdfae6e4bfe494abfbde3d

test:
  secret_key_base: 1fb60f1cd2842d3cc800fef05d641e0b8c6d26f372d5634fd3c1b581925d74b17b5fddde02e30278f28caed428d6022c4c8bbeb151ef56651512f87189e60dd3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
